
import { Inter } from 'next/font/google';
import AppMui from '@/Mui/Mui'; // Ensure this import path is correct
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    template: '%s | CodeMax',
    default: 'home',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <AppMui>
          {children}
        </AppMui>
      </body>
    </html>
  );
}
